name: 'Create Infra with Terraform'

on:
  push:
    branches: [ main ]
    paths: .github/workflows/terraform-deploy-env.yaml
  pull_request:
    branches:  none # [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
env:
  STORAGE_ACCOUNT_NAME_DEV: sa1221dev
  STORAGE_ACCOUNT_NAME_UAT: sa1221uat
  STORAGE_ACCOUNT_NAME_PROD: sa1221prod
  RESOURCE_GROUP_NAME: rg-terraform-state
  CONTAINER_NAME: tfstate
  BLOB_NAME: terraform.tfstate
  WORKING_DIRECTORY: terraform
  
jobs:
  deploy-dev:
    name: Deploy Infra to Development
    uses: ibrt2016/IntactTerraformDemo/.github/workflows/terraform-devops.yaml@main
    with:
      environment: Development
      STORAGE_ACCOUNT_NAME: "${{ env.STORAGE_ACCOUNT_NAME_DEV }}"
      RESOURCE_GROUP_NAME: "${{ env.RESOURCE_GROUP_NAME }}"
      CONTAINER_NAME: "${{ env.CONTAINER_NAME }}"
      BLOB_NAME: "${{ env.BLOB_NAME }}"
      WORKING_DIRECTORY: "${{ env.WORKING_DIRECTORY }}"
    # secrets:
    #   ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
    #   ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET}}
    #   ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID}}
    #   ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  deploy-uat:
    name: Deploy Infra to UAT
    uses: ibrt2016/IntactTerraformDemo/.github/workflows/terraform-devops.yaml@main
    with:
      environment: UserAcceptanceTesting
      STORAGE_ACCOUNT_NAME: "${{ env.STORAGE_ACCOUNT_NAME_UAT }}"
      RESOURCE_GROUP_NAME: "${{ env.RESOURCE_GROUP_NAME }}"
      CONTAINER_NAME: "${{ env.CONTAINER_NAME }}"
      BLOB_NAME: "${{ env.BLOB_NAME }}"
      WORKING_DIRECTORY: "${{ env.WORKING_DIRECTORY }}"

  deploy-prod:
    name: Deploy Infra to Production
    uses: ibrt2016/IntactTerraformDemo/.github/workflows/terraform-devops.yaml@main
    with:
      environment: Production
      STORAGE_ACCOUNT_NAME: "${{ env.STORAGE_ACCOUNT_NAME_PROD }}"
      RESOURCE_GROUP_NAME: "${{ env.RESOURCE_GROUP_NAME }}"
      CONTAINER_NAME: "${{ env.CONTAINER_NAME }}"
      BLOB_NAME: "${{ env.BLOB_NAME }}"
      WORKING_DIRECTORY: "${{ env.WORKING_DIRECTORY }}"
    needs: [deploy-dev, deploy-uat]

